server:
  port: 9090
spring:
  cloud:
    gateway:
      routes:
        - id: ODERSERVICE
          uri: lb://ORDERSERVICE
          predicates:
            - Path=/order/**
        - id: AUTH-SERVICE
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**
        - id: PAYMENTSERVICE
          uri: lb://PAYMENTSERVICE
          predicates:
            - Path=/payment/**
        - id: PRODUCTSERVICE
          uri: lb://PRODUCTSERVICE
          predicates:
            - Path=/product/**
  
jwt:
  secret: mySecretKey
  expireMs: 120000
  refrEshexpireMs: 120000
logging:
  pattern:
    # Logging pattern containing traceId and spanId; no longer provided through Sleuth by default
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"   
